### PR TITLE
Fix purpleAirToFirestore Update() error

### LINKED ISSUE #576: Error in purpleAirToFirestore cloud function
Error: Update() requires either a single JavaScript object or an alternating list of field/value 
pairs that can be followed by an optional precondition. At least one field must be updated.

It happens locally and is being logged in Firestore

### PR DESCRIPTION
**Pull request by CarsonHerness**
This PR adds a `lastUpdated` field for every update to a sensor's doc. This is necessary because the purpleAirToFirestore function was throwing errors if `update` was called but no fields were actually updated. Now, every time update is called, `lastUpdated` is set to the server timestamp.

This PR also:

- Fixes a bug in the type of the aqiBufferElement
- Fixes some documentation for the aqiBufferElement
- Adds TODOs for where a reason that a sensor is down can be determined
- Removes previous helper function to ensure that a `purpleAirId` is a number since all sensor docs have now been converted to using numbers, and all newly added sensors will also use a number

Closes #576

### CODE REVIEW

File: functions/src/aqi-calculation/purple-air-response.ts [hunk 1]
```diff
@@ -91,7 +90,7 @@ async function purpleAirToFirestore(): Promise<void> {
 
     // Get the existing data from Firestore for this sensor
     const sensorDocData = sensorDoc.data() ?? {};
-    const purpleAirId = getPurpleAirId(sensorDocData.purpleAirId);
+    const purpleAirId: number = sensorDocData.purpleAirId;
```
Comment (akampen) [inline functions/src/aqi-calculation/purple-air-response.ts:93]: In this PR I don't see a place where we check for numbers (so I assume it happened in a recent PR), what new code ensured that we don't need to do this check anymore?

File: functions/src/aqi-calculation/purple-air-response.ts [hunk 2]
```diff
@@ -133,7 +141,6 @@ async function purpleAirToFirestore(): Promise<void> {
         sensorDocUpdate.latitude = reading.latitude;
         sensorDocUpdate.longitude = reading.longitude;
         sensorDocUpdate.name = reading.name;
-        sensorDocUpdate.purpleAirId = reading.id;
```
Comment (akampen) [inline functions/src/aqi-calculation/purple-air-response.ts:136]: is this removed just because it's redundant? Could PA ever change a PA ID?

File: functions/src/aqi-calculation/purple-air-response.ts (hunk 1 above)
Comment (CarsonHerness) [reply functions/src/aqi-calculation/purple-air-response.ts:93]: I manually checked all sensor docs in Firestore used numbers, so there's no longer a mix.

File: functions/src/aqi-calculation/purple-air-response.ts (hunk 2 above)
Comment (CarsonHerness) [reply functions/src/aqi-calculation/purple-air-response.ts:136]: This was my way of automatically changing the sensor docs to use numbers instead of strings for purpleAirId, but it's no longer necessary. The PurpleAir ID won't change in a sensor call

**Review by akampen — APPROVED** [review]
